---
title: "CodeBook"
author: "Ermeson Andrade"
date: "25/11/2020"
output: html_document
---

# Merges the training and the test sets to create one data set. {.tabset}

## Reading training data.

```{rchunk_name, results="hide"}
x_train <- read.table("https://www.dropbox.com/s/o2r22wn2boxsi57/X_train.txt?dl=1")
y_train <- read.table("https://www.dropbox.com/s/7525xmeflrinwlt/y_train.txt?dl=1")
subject_train <- read.table("https://www.dropbox.com/s/8sze3wg29dzjjrf/subject_train.txt?dl=1")

```

## Reading testing data.

```{rchunk_name, results="hide"}
x_test <- read.table("https://www.dropbox.com/s/udtsyaie5gwvjwb/X_test.txt?dl=1")
y_test <- read.table("https://www.dropbox.com/s/ngj1wj5ek6e2qfw/y_test.txt?dl=1")
subject_test <- read.table("https://www.dropbox.com/s/ru7p9dfchvn1ap4/subject_test.txt?dl=1")
```

## Reading feature information.
```{rchunk_name, results="hide"}
features <- read.table('https://www.dropbox.com/s/78rcaq20jlwxnln/features.txt?dl=1')

```

##  Reading activity information.
```{rchunk_name, results="hide"}
activityLabels = read.table('https://www.dropbox.com/s/8qwxt96u4p6101s/activity_labels.txt?dl=1')

```

## Assigning names to the columns.

```{rchunk_name, results="hide"}
colnames(x_train) <- features$V2
colnames(y_train) <-"activityId"
colnames(subject_train) <- "subjectId"

colnames(x_test) <- features$V2 
colnames(y_test) <- "activityId"
colnames(subject_test) <- "subjectId"

colnames(activityLabels) <- c('activityId','activityType')

```

## Merging all data in one set.

```{rchunk_name, results="hide"}
merge_train <- cbind(y_train, subject_train, x_train)
merge_test <- cbind(y_test, subject_test, x_test)
all <- rbind(merge_train, merge_test)

```

## About variables

`x_train`, `y_train`, `x_test`, `y_test`, `subject_train`, `subject_test`, `features`, and `activityLabels` contain the data from the downloaded files.

`merge_train` and  `merge_test` contain merged data from the training and test data, respectively.

`all` contains all the merged data.

# Extracts only the measurements on the mean and standard deviation for each measurement. {.tabset}

## Extracting only the mean and standard deviation for the measures.

```{rchunk_name, results="hide"}
colNames <- colnames(all)
onlyMeanAndStd <-all[,grepl("activityId|subjectId|mean|std",colNames)]

```
## About variables
`colNames` contains column names.

`onlyMeanAndStd` contains only the data concerning the mean and standard deviation.


# Uses descriptive activity names to name the activities in the data set.{.tabset}

## Adding activities names. 
```{rchunk_name, results="hide"}

activityWithNames <- merge(onlyMeanAndStd, activityLabels,
                              by='activityId',
                              all.x=TRUE)

```
## About variables

`activityWithNames` contains the data set with the activity names.

# Appropriately labels the data set with descriptive variable names.{.tabset}

## Replacing abbreviations by descriptive names.

```{rchunk_name, results="hide"}
names(activityWithNames)<-gsub("^t", "time", names(activityWithNames))
names(activityWithNames)<-gsub("^f", "frequency", names(activityWithNames))
names(activityWithNames)<-gsub("Acc", "Accelerometer", names(activityWithNames))
names(activityWithNames)<-gsub("Gyro", "Gyroscope", names(activityWithNames))
names(activityWithNames)<-gsub("Mag", "Magnitude", names(activityWithNames))
names(activityWithNames)<-gsub("BodyBody", "Body", names(activityWithNames))

```

# From the data set in step 4, creates a second, independent tidy data set with  the average of each variable for each activity and each subject. {.tabset}


## Creating new data set.
```{rchunk_name, results="hide"}

tidy2<-activityWithNames%>%
  group_by(activityId, subjectId) %>%
  summarise_all(funs(mean))

```
## About variables

`tidy2` contains the new data with the average of each variable for each activity and each subject.